name: perform ci and cd

on: [push, pull_request]

jobs:
  build:
    name: build executable file
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/checkout@v2

      - name: setup go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
          
      - name: build go
        run: go build -o main .

      - name: convert to zip
        uses: actions/checkout@v2
        uses: papeloto/action-zip@v1
        with:
          files: main
          dest: result.zip
      
      - name: setup telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: docker image
          document: result.zip