name: perform ci and cd

on: [push, pull_request]

jobs:
  build:
    name: build executable file
    runs-on: ubuntu-latest
    
    steps:
    
      # SETUP GO ENVIRONMENT
      - name: checkout go
        uses: actions/checkout@v2
        
      - name: setup go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
        
      # BUILD EXECUTABLE GO FILE
      - name: build go
        run: env GOOS=darwin GOARH=amd64 go build -v ./...
        
      # LOGIN THEN BUILD AND PUSH TO DOCKER HUB
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
         
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: erwindosianipar/automation:$(date +%Y%m%d%H%M)
          
      - name: docker build push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      # NOTIFY TO TELEGRAM
      - name: use telegram engine
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: docker image has been uploaded to docker hub
          