name: perform ci and cd

on: [push, pull_request]

jobs:
  build:
    name: build executable file
    runs-on: ubuntu-latest

    steps:

      # SETUP GO ENVIRONMENT
      - name: checkout go
        uses: actions/checkout@v2

      - name: setup go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
            
      - name: build executable file
        run: env GOOS=darwin GOARH=amd64 go build -o main .

      # PUSH DOCKER IMAGE TO DOCKER HUB
      - name: login docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: extract meta data for docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: erwindosianipar/automation

      - name: build and push docker
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # NOTIFY TO TELEGRAM
      - name: use telegram engine
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: docker image has been uploaded to docker hub
