name: perform ci and cd

on: [push, pull_request]

jobs:
  build:
    name: build executable file
    runs-on: ubuntu-latest
    
    steps:
    
      # SETUP GO ENVIRONMENT
      - name: checkout go
        uses: actions/checkout@v2
        
      - name: setup go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
          
      # BUILD EXECUTABLE GO FILE
      - name: build go
        run: env GOOS=darwin GOARH=amd64 go build -o main .
        
      # LOGIN THEN BUILD AND PUSH TO DOCKER HUB
      - name: login to docker hub
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $USERNAME -p $PASSWORD
      
      - name: build docker image
        run: docker build -t erwindosianipar/automation:$(date +%s) .
        
      - name: push docker image
        run: docker push erwindosianipar/automation
      
      # NOTIFY TO TELEGRAM
      - name: use telegram engine
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: docker image has been uploaded to docker hub
          