name: perform ci and cd

on: [push, pull_request]

jobs:
  build:
    name: build executable file
    runs-on: [self-hosted, ubuntu-latest]

    steps:
      - name: setup go
        uses: actions/checkout@v2

      - name: setup go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
            
      - name: build go
        run: env GOOS=darwin GOARH=amd64 go build -o main .

      - name: use telegram engine
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: docker image
          document: main